plugins {
    id 'java-library'
}

dependencies {
    api libs.jackson.databind
    api libs.jackson.datatype.jsr310

    compileOnly libs.lombok
    annotationProcessor libs.lombok

    testCompileOnly libs.lombok
    testAnnotationProcessor libs.lombok
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
    testImplementation 'org.assertj:assertj-core:3.27.2'
}
