plugins {
    id 'java-library'
}

dependencies {
    api project(':libraries:explanation-ir')
    api libs.exp4j

    compileOnly libs.lombok
    annotationProcessor libs.lombok

    testCompileOnly libs.lombok
    testAnnotationProcessor libs.lombok
    testImplementation libs.junit.jupiter
    testImplementation libs.assertj.core
}
