plugins {
    id 'java-library'
}

dependencies {
    api project(':libraries:explanation-ir')
    api project(':libraries:math-core')
    api project(':libraries:reasoning-core')
    api libs.json.schema.validator

    compileOnly libs.lombok
    annotationProcessor libs.lombok

    testCompileOnly libs.lombok
    testAnnotationProcessor libs.lombok
    testImplementation libs.junit.jupiter
    testImplementation libs.assertj.core
}
